asp-net-mvc-intro/Models/ErrorViewModel.cs
using System;

namespace asp_net_mvc_intro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

asp-net-mvc-intro/Models/Producto.cs
using System;

namespace asp_net_mvc_intro.Models
{
    public class Producto
    {
        public Producto()
        {

        }

        public Producto(Guid id, string descripcion, int orden, decimal precio)
        {
            Id = id;
            Descripcion = descripcion;
            Orden = orden;
            Precio = precio;
        }

        public Guid Id { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
        public decimal Precio { get; set; }
    }
}

asp-net-mvc-intro/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace asp_net_mvc_intro.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

asp-net-mvc-intro/Controllers/RetornosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using asp_net_mvc_intro.Models;
using Microsoft.AspNetCore.Mvc;

namespace asp_net_mvc_intro.Controllers
{
    public class RetornosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public string EjemploString()
        {
            return "esto es un string que retorno";
        }

        public IActionResult EjemploStringConHtml()
        {
            return Content("<html><head></head><body style='background-color:yellow'>Prueba de string con contenido html</body></html>", "text/html");
        }

        public IActionResult EjemploJson()
        {
            Producto producto = new Producto
            {
                Id = Guid.NewGuid(),
                Descripcion = "Un producto de prueba",
                Orden = 1,
                Precio = 80M
            };

            return Json(producto);
        }

        public IActionResult EjemploVista()
        {
            return View();
        }

        public IActionResult EjemploVistaSinLayout()
        {
            return View();
        }
    }
}

asp-net-mvc-intro/Controllers/UsandoModelosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using asp_net_mvc_intro.Models;
using Microsoft.AspNetCore.Mvc;

namespace asp_net_mvc_intro.Controllers
{
    public class UsandoModelosController : Controller
    {
        private readonly static List<Producto> _productos = new List<Producto>()
        {
            new Producto(Guid.NewGuid(), "Café", 1, 200M),
            new Producto(Guid.NewGuid(), "Té", 2, 65M),
            new Producto(Guid.NewGuid(), "Azúcar", 3, 30M),
            new Producto(Guid.NewGuid(), "Edulcorante", 4, 50M),
            new Producto(Guid.NewGuid(), "Yerba", 5, 120M),
            new Producto(Guid.NewGuid(), "Galletitas", 6, 100M),
            new Producto(Guid.NewGuid(), "Bizcochos", 7, 80M),
        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListaDeProductos()
        {
            return View(_productos);
        }

        public IActionResult UnProducto(Guid id)
        {
            Producto producto = _productos.First(producto => producto.Id == id);
            return View(producto);
        }

        [HttpGet]
        public IActionResult AgregarProducto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AgregarProducto(Producto producto)
        {
            producto.Id = Guid.NewGuid();
            producto.Orden = _productos.Max(producto => producto.Orden) + 1;
            _productos.Add(producto);
            return RedirectToAction(nameof(ListaDeProductos));
        }

        [HttpGet]
        public IActionResult EditarProducto(Guid id)
        {
            Producto producto = _productos.First(producto => producto.Id == id);
            return View(producto);
        }

        // Este método debería ser PUT pero como usamos formularios html usamos POST
        [HttpPost]
        public IActionResult EditarProducto(Producto producto)
        {
            Producto productoExistente = _productos.First(prod => prod.Id == producto.Id);
            productoExistente.Descripcion = producto.Descripcion;
            productoExistente.Precio = producto.Precio;

            return RedirectToAction(nameof(ListaDeProductos));
        }
    }
}

asp-net-mvc-intro/Views/Retornos/EjemploVista.cshtml
@{
    ViewData["Title"] = "Ejemplo usando vista";

    // este es un ejemplo de una forma de usar el ViewData para poner info que se usará en el Layout
    ViewData["estiloNav"] = "bg-dark";
}

<h1>Ejemplo usando vista</h1>

<div>
    Esta vista utiliza el layout que se encuentra en la carpeta Shared: <span class="badge badge-dark">Views/Shared/_Layout.cshtml</span>.
    El contenido que haya en esta vista "EjemploVista.cshtml" al momento de generar la página html
    que se le muestra al usuario se insertará donde está el método <span class="badge badge-danger">RenderBody()</span>
</div>

asp-net-mvc-intro/Views/Retornos/EjemploVistaSinLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ejemplo usando Vista sin layout</title>
</head>
<body>
    <div>
        esta vista no tiene un layout, con lo cual el html que tenga dentro es TODO el html que utiliza
    </div>
</body>
</html>

asp-net-mvc-intro/Views/Retornos/Index.cshtml
@{
    ViewData["Title"] = "Tipos de retornos";
}

<div class="text-center">
    <h1 class="display-4">Tipos de retornos de las acciones</h1>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ejemplo retornando string</h5>
                    <a asp-controller="Retornos" asp-action="EjemploString" target="_blank" class="card-link">link</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ejemplo retornando string con contenido html</h5>
                    <a asp-controller="Retornos" asp-action="EjemploStringConHtml" target="_blank" class="card-link">link</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ejemplo retornando json</h5>
                    <a asp-controller="Retornos" asp-action="EjemploJson" target="_blank" class="card-link">link</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ejemplo retornando una vista</h5>
                    <a asp-controller="Retornos" asp-action="EjemploVista" target="_blank" class="card-link">link</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ejemplo retornando una vista sin layout</h5>
                    <a asp-controller="Retornos" asp-action="EjemploVistaSinLayout" target="_blank" class="card-link">link</a>
                </div>
            </div>
        </div>
    </div>
</div>

asp-net-mvc-intro/Views/Shared/_Layout.cshtml
@{
    string estiloNav = (string)ViewData["estiloNav"];

    if (string.IsNullOrEmpty(estiloNav))
    {
        estiloNav = "bg-white";
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET MVC Core Intro</title>

    <!-- getbootstrap.com -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="@estiloNav navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET MVC Core Intro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Retornos" asp-action="Index">Retornos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UsandoModelos" asp-action="Index">Usando Modelos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASP.NET MVC Core Intro
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>