usando-seguridad/Models/Cuenta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace usando_seguridad.Models
{
    public class Cuenta
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage ="El campo {0} es requerido")]
        [MaxLength(50, ErrorMessage = "El campo {0} admite un máximo de {1} caracteres")]
        [MinLength(2, ErrorMessage = "El campo {0} admite un mínimo de {1} caracteres")]
        public string Numero { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        public decimal Balance { get; set; }

        public List<ClienteCuenta> Clientes { get; set; }

        [ForeignKey(nameof(Sucursal))]
        public Guid SucursalId { get; set; }
        public Sucursal Sucursal { get; set; }

        [ForeignKey(nameof(Moneda))]
        public Guid MonedaId { get; set; }
        public Moneda Moneda { get; set; }

        public List<Movimiento> Movimientos { get; set; }
    }
}

usando-seguridad/Models/Movimiento.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace usando_seguridad.Models
{
    public class Movimiento
    {
        [Key]
        public Guid Id { get; set; }

        public DateTime Fecha { get; set; }

        public decimal Monto { get; set; }

        [ForeignKey(nameof(Cuenta))]
        public Guid CuentaId { get; set; }
        public Cuenta Cuenta { get; set; }

        [ForeignKey(nameof(Cliente))]
        public Guid ClienteId { get; set; }
        public Cliente Cliente { get; set; }
    }
}

usando-seguridad/Controllers/CuentasController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using usando_seguridad.Database;
using usando_seguridad.Models;

namespace usando_seguridad.Controllers
{
    [Authorize] // Solamente debe estar logueado
    public class CuentasController : Controller
    {
        private readonly SeguridadDbContext _context;

        public CuentasController(SeguridadDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Administrador,Cliente")] // tanto un admin como un cliente pueden acceder
        public async Task<IActionResult> Index()
        {
            var seguridadDbContext = _context.Cuentas.Include(c => c.Moneda).Include(c => c.Sucursal);
            return View(await seguridadDbContext.ToListAsync());
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuentas
                .Include(c => c.Moneda)
                .Include(c => c.Sucursal)
                .Include(cuenta => cuenta.Clientes).ThenInclude(clienteCuenta => clienteCuenta.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            ViewData["MonedaId"] = new SelectList(_context.Monedas, "Id", "Codigo");
            ViewData["SucursalId"] = new SelectList(_context.Sucursales, "Id", "Nombre");
            ViewData["Clientes"] = new MultiSelectList(_context.Clientes, nameof(Cliente.Id), nameof(Cliente.Descripcion));
            return View();
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cuenta cuenta, Guid[] clienteIds, Guid titularDeCuenta)
        {
            if (ModelState.IsValid)
            {
                cuenta.Id = Guid.NewGuid();

                foreach (Guid clienteId in clienteIds)
                {
                    var cliente = new ClienteCuenta()
                    {
                        Id = Guid.NewGuid(),
                        ClienteId = clienteId,
                        CuentaId = cuenta.Id,
                        EsTitular = clienteId.Equals(titularDeCuenta)
                    };

                    _context.Add(cliente);
                }

                _context.Add(cuenta);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonedaId"] = new SelectList(_context.Monedas, "Id", "Codigo", cuenta.MonedaId);
            ViewData["SucursalId"] = new SelectList(_context.Sucursales, "Id", "Nombre", cuenta.SucursalId);
            ViewData["Clientes"] = new MultiSelectList(_context.Clientes, nameof(Cliente.Id), nameof(Cliente.Descripcion));
            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = _context.Cuentas
                .Include(cuenta => cuenta.Clientes)
                .FirstOrDefault(cuenta => cuenta.Id == id);

            if (cuenta == null)
            {
                return NotFound();
            }

            var clienteIds = cuenta.Clientes.Select(clienteCuenta => clienteCuenta.ClienteId);

            ViewData["MonedaId"] = new SelectList(_context.Monedas, "Id", "Codigo", cuenta.MonedaId);
            ViewData["SucursalId"] = new SelectList(_context.Sucursales, "Id", "Nombre", cuenta.SucursalId);
            ViewData["Clientes"] = new MultiSelectList(_context.Clientes, nameof(Cliente.Id), nameof(Cliente.Dni), clienteIds);

            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, Cuenta cuenta, Guid[] clienteIds, Guid titularDeCuenta)
        {
            if (id != cuenta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Obtengo la cuenta desde la base de datos
                    var clienteCuentas = _context.ClienteCuentas.Where(clienteCuenta => clienteCuenta.CuentaId == id);

                    _context.RemoveRange(clienteCuentas);

                    // Crea todas las relaciones con Clientes para la cuenta editada.
                    foreach (Guid clienteId in clienteIds)
                    {
                        var cliente = new ClienteCuenta()
                        {
                            Id = Guid.NewGuid(),
                            ClienteId = clienteId,
                            CuentaId = cuenta.Id,
                            EsTitular = clienteId.Equals(titularDeCuenta)
                        };

                        _context.Add(cliente);
                    }

                    _context.Update(cuenta);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CuentaExists(cuenta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonedaId"] = new SelectList(_context.Monedas, "Id", "Codigo", cuenta.MonedaId);
            ViewData["SucursalId"] = new SelectList(_context.Sucursales, "Id", "Nombre", cuenta.SucursalId);
            ViewData["Clientes"] = new MultiSelectList(_context.Clientes, nameof(Cliente.Id), nameof(Cliente.Dni), clienteIds);

            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuentas
                .Include(c => c.Moneda)
                .Include(c => c.Sucursal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cuenta = await _context.Cuentas.FindAsync(id);
            _context.Cuentas.Remove(cuenta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #region Acciones de Cliente

        [Authorize(Roles = nameof(Rol.Cliente))] // solamente puede acceder un cliente
        [HttpGet]
        public IActionResult MisCuentas()
        {
            var username = User.Identity.Name;
            var cliente = _context.Clientes
                .Include(cliente => cliente.Cuentas).ThenInclude(clienteCuenta => clienteCuenta.Cuenta).ThenInclude(cuenta => cuenta.Moneda)
                .FirstOrDefault(cliente => cliente.Username == username);

            return View(cliente);
        }

        [Authorize(Roles = nameof(Rol.Cliente))]
        [HttpGet]
        public IActionResult Depositar(Guid id)
        {
            var cuenta = _context.Cuentas.Find(id);
            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Cliente))]
        [HttpPost]
        public IActionResult Depositar(Guid id, decimal monto)
        {
            var cuenta = _context.Cuentas.Find(id);

            if (monto <= 0)
            {
                ViewBag.Error = "El monto debe ser un valor positivo";
                return View(cuenta);
            }

            cuenta.Balance += monto;

            var clienteId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var movimiento = new Movimiento()
            {
                Id = Guid.NewGuid(),
                ClienteId = clienteId,
                CuentaId = cuenta.Id,
                Fecha = DateTime.Now,
                Monto = monto
            };

            _context.Add(movimiento);

            _context.SaveChanges();

            return RedirectToAction(nameof(MisCuentas));
        }

        [Authorize(Roles = nameof(Rol.Cliente))]
        [HttpGet]
        public IActionResult Extraer(Guid id)
        {
            var cuenta = _context.Cuentas.Find(id);
            return View(cuenta);
        }

        [Authorize(Roles = nameof(Rol.Cliente))]
        [HttpPost]
        public IActionResult Extraer(Guid id, decimal monto)
        {
            var cuenta = _context.Cuentas.Find(id);

            if(cuenta.Balance < monto)
            {
                ViewBag.Error = "No dispone de fondos";
                return View(cuenta);
            }

            cuenta.Balance -= monto;

            var clienteId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var movimiento = new Movimiento()
            {
                Id = Guid.NewGuid(),
                ClienteId = clienteId,
                CuentaId = cuenta.Id,
                Fecha = DateTime.Now,
                Monto = monto * -1
            };

            _context.Add(movimiento);

usando-seguridad/Views/Cuentas/Create.cshtml
@model usando_seguridad.Models.Cuenta

@{
    ViewData["Title"] = "Alta de cuenta";
}

<h4>Alta de Cuenta</h4>

<hr />

<div class="row">
    <div class="col-md-6 offset-3">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SucursalId" class="control-label"></label>
                <select asp-for="SucursalId" class="form-control selectpicker" asp-items="ViewBag.SucursalId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MonedaId" class="control-label"></label>
                <select asp-for="MonedaId" class="form-control selectpicker" asp-items="ViewBag.MonedaId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Clientes</label>
                <select name="clienteIds" class="form-control selectpicker" asp-items="ViewBag.Clientes" multiple></select>
            </div>
            <div class="form-group">
                <label class="control-label">Titular de cuenta</label>
                <select name="titularDeCuenta" class="form-control selectpicker" asp-items="ViewBag.Clientes"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

usando-seguridad/Views/Cuentas/Delete.cshtml
@model usando_seguridad.Models.Cuenta

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cuenta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sucursal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sucursal.Nombre)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Moneda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Moneda.Codigo)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

usando-seguridad/Views/Cuentas/Depositar.cshtml
@model Cuenta

@{
    ViewData["Title"] = "Depositar";
}

<h1>Depositar en cuenta @Model.Numero</h1>


<form method="post" asp-controller="Cuentas" asp-action="Depositar">
    <input type="hidden" name="id" value="@Model.Id" /> 
    <div class="form-group">
        <label for="monto" class="control-label">Monto</label>
        <input name="monto" type="number" class="form-control" />
        <span class="text-danger">@ViewBag.Error</span>
    </div>

    <button type="submit" class="btn btn-success">
        Depositar
    </button>
</form>

usando-seguridad/Views/Cuentas/Details.cshtml
@model usando_seguridad.Models.Cuenta

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cuenta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sucursal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sucursal.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Moneda)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Moneda.Codigo)
        </dd>
        <dt class="col-sm-2">
            Clientes
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (ClienteCuenta clienteCuenta in Model.Clientes)
                {
                    <li>
                        <i class="fas "></i>
                        @clienteCuenta.Cliente.Apellido, @clienteCuenta.Cliente.Nombre - DNI: @clienteCuenta.Cliente.Dni
                        <i class="fas @(clienteCuenta.EsTitular ? "fa-check-circle text-success" : "fa-ban text-danger")"></i>
                    </li>
                }
            </ul>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

usando-seguridad/Views/Cuentas/Edit.cshtml
@model Cuenta

@{
    ViewData["Title"] = "Edición de cuenta";
}

<h4>Editar la cuenta</h4>

<hr />

<div class="row">
    <div class="col-md-6 offset-3">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SucursalId" class="control-label"></label>
                <select asp-for="SucursalId" class="form-control" asp-items="ViewBag.SucursalId"></select>
                <span asp-validation-for="SucursalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonedaId" class="control-label"></label>
                <select asp-for="MonedaId" class="form-control" asp-items="ViewBag.MonedaId"></select>
                <span asp-validation-for="MonedaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Clientes</label>
                <select name="clienteIds" class="form-control" asp-items="ViewBag.Clientes" multiple></select>
            </div>
            <div class="form-group">
                <label class="control-label">Titular de cuenta</label>
                <select name="titularDeCuenta" class="form-control selectpicker" asp-items="ViewBag.Clientes"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

usando-seguridad/Views/Cuentas/Extraer.cshtml
@model Cuenta

@{
    ViewData["Title"] = "Extraer";
}

<h1>Extraer de la cuenta @Model.Numero</h1>


<form method="post" asp-controller="Cuentas" asp-action="Extraer">
    <input type="hidden" name="id" value="@Model.Id" />
    <div class="form-group">
        <label for="monto" class="control-label">Monto</label>
        <input name="monto" type="number" class="form-control" />
        <span class="text-danger">@ViewBag.Error</span>
    </div>

    <button type="submit" class="btn btn-success">
        Extraer
    </button>
</form>

usando-seguridad/Views/Cuentas/Index.cshtml
@model IEnumerable<usando_seguridad.Models.Cuenta>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sucursal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Moneda)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sucursal.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moneda.Codigo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

usando-seguridad/Views/Cuentas/MisCuentas.cshtml
@model Cliente

@{
    ViewData["Title"] = $"Cuentas de {Model.Nombre} {Model.Apellido}";
}

<h2><i class="fas fa-wallet text-success"></i> Cuentas de @Model.Nombre @Model.Apellido</h2>

<table class="table table-striped table-sm">
    <thead>
        <tr>
            <th>Número</th>
            <th>Balance</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Cuenta cuenta in Model.Cuentas.Select(clienteCuenta => clienteCuenta.Cuenta))
        {
            <tr>
                <td>@cuenta.Numero</td>
                <td>(@cuenta.Moneda.Codigo) @cuenta.Balance.ToString("N2")</td>
                <td>
                    <a class="btn" asp-controller="Cuentas" asp-action="Movimientos" asp-route-id="@cuenta.Id" title="Ver Movimientos" data-toggle="tooltip">
                        <i class="fas fa-eye text-primary"></i>
                    </a>
                    <a class="btn" asp-controller="Cuentas" asp-action="Depositar" asp-route-id="@cuenta.Id" title="Depositar" data-toggle="tooltip">
                        <i class="fas fa-money-bill-wave text-success"></i>
                    </a>
                    <a class="btn" asp-controller="Cuentas" asp-action="Extraer" asp-route-id="@cuenta.Id" title="Extraer" data-toggle="tooltip">
                        <i class="fas fa-money-bill-wave text-danger"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

usando-seguridad/Views/Cuentas/Movimientos.cshtml
@model Cuenta

@{
    ViewData["Title"] = $"Movimientos de cuenta {Model.Numero}";
}

<h2><i class="fas fa-wallet text-success"></i> Movimientos de cuenta @Model.Numero</h2>

<table class="table table-striped table-sm">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Monto</th>
            <th>Cliente</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Movimiento movimiento in Model.Movimientos)
        {
            <tr>
                <td>@movimiento.Fecha</td>
                <td class="@(movimiento.Monto < 0 ? "text-danger" : "text-success")">$ @movimiento.Monto.ToString("N2")</td>
                <td>@movimiento.Cliente.Apellido @movimiento.Cliente.Nombre</td>
            </tr>
        }
    </tbody>
</table>